// This file is automatically generated.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createSupabaseClient() {
  // უსაფრთხოდ იღებს პროცესის ცვლადს მხოლოდ მაშინ, თუ ის არსებობს (SSR/სერვერზე)
  const processEnvUrl = typeof process !== 'undefined' && process.env ? process.env.SUPABASE_URL : undefined;
  const processEnvKey = typeof process !== 'undefined' && process.env ? process.env.SUPABASE_PUBLISHABLE_KEY : undefined;

  const SUPABASE_URL = 
    import.meta.env.VITE_SUPABASE_URL || 
    processEnvUrl || 
    "https://wmwfciwyxvhmuxngyese.supabase.co";

  const SUPABASE_PUBLISHABLE_KEY = 
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 
    processEnvKey || 
    "sb_publishable_aAxRNvBoxWGd2zm6TXXRKg_-6WFvCNh";

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
